// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/compare.dart';
import 'api/score.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -259238892;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_nightingale_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiScoreBridgeHello();

  String crateApiScoreFindProjectRoot({required String startPath});

  Future<ComparisonPageResult> crateApiCompareGetComparison({
    required String projectRoot,
    required String fixtureName,
    required int pageNum,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<List<OgFixtureInfo>> crateApiCompareListOgFixtures({
    required String projectRoot,
  });

  List<ScoreFileEntry> crateApiScoreListScoreFiles({required String directory});

  int crateApiScoreRenderCommandCount({required List<int> data});

  Future<RenderCommandDto> crateApiScoreRenderCommandDtoDefault();

  Future<List<RenderCommandDto>> crateApiScoreRenderNglFromBytes({
    required List<int> data,
  });

  Future<List<RenderCommandDto>> crateApiScoreRenderNotelistFromText({
    required String text,
  });

  Future<List<RenderCommandDto>> crateApiScoreRenderScoreFromPath({
    required String path,
  });

  Future<List<RenderCommandDto>> crateApiScoreRenderScoreFromPathLandscape({
    required String path,
    required bool landscape,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiScoreBridgeHello() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScoreBridgeHelloConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScoreBridgeHelloConstMeta =>
      const TaskConstMeta(debugName: "bridge_hello", argNames: []);

  @override
  String crateApiScoreFindProjectRoot({required String startPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(startPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScoreFindProjectRootConstMeta,
        argValues: [startPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScoreFindProjectRootConstMeta =>
      const TaskConstMeta(
        debugName: "find_project_root",
        argNames: ["startPath"],
      );

  @override
  Future<ComparisonPageResult> crateApiCompareGetComparison({
    required String projectRoot,
    required String fixtureName,
    required int pageNum,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectRoot, serializer);
          sse_encode_String(fixtureName, serializer);
          sse_encode_i_32(pageNum, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_comparison_page_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCompareGetComparisonConstMeta,
        argValues: [projectRoot, fixtureName, pageNum],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCompareGetComparisonConstMeta =>
      const TaskConstMeta(
        debugName: "get_comparison",
        argNames: ["projectRoot", "fixtureName", "pageNum"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<OgFixtureInfo>> crateApiCompareListOgFixtures({
    required String projectRoot,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectRoot, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_og_fixture_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCompareListOgFixturesConstMeta,
        argValues: [projectRoot],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCompareListOgFixturesConstMeta =>
      const TaskConstMeta(
        debugName: "list_og_fixtures",
        argNames: ["projectRoot"],
      );

  @override
  List<ScoreFileEntry> crateApiScoreListScoreFiles({
    required String directory,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(directory, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_score_file_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScoreListScoreFilesConstMeta,
        argValues: [directory],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScoreListScoreFilesConstMeta =>
      const TaskConstMeta(
        debugName: "list_score_files",
        argNames: ["directory"],
      );

  @override
  int crateApiScoreRenderCommandCount({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScoreRenderCommandCountConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScoreRenderCommandCountConstMeta =>
      const TaskConstMeta(
        debugName: "render_command_count",
        argNames: ["data"],
      );

  @override
  Future<RenderCommandDto> crateApiScoreRenderCommandDtoDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_render_command_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScoreRenderCommandDtoDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScoreRenderCommandDtoDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "render_command_dto_default",
        argNames: [],
      );

  @override
  Future<List<RenderCommandDto>> crateApiScoreRenderNglFromBytes({
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_render_command_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScoreRenderNglFromBytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScoreRenderNglFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "render_ngl_from_bytes",
        argNames: ["data"],
      );

  @override
  Future<List<RenderCommandDto>> crateApiScoreRenderNotelistFromText({
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_render_command_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScoreRenderNotelistFromTextConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScoreRenderNotelistFromTextConstMeta =>
      const TaskConstMeta(
        debugName: "render_notelist_from_text",
        argNames: ["text"],
      );

  @override
  Future<List<RenderCommandDto>> crateApiScoreRenderScoreFromPath({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_render_command_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScoreRenderScoreFromPathConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScoreRenderScoreFromPathConstMeta =>
      const TaskConstMeta(
        debugName: "render_score_from_path",
        argNames: ["path"],
      );

  @override
  Future<List<RenderCommandDto>> crateApiScoreRenderScoreFromPathLandscape({
    required String path,
    required bool landscape,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_bool(landscape, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_render_command_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScoreRenderScoreFromPathLandscapeConstMeta,
        argValues: [path, landscape],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScoreRenderScoreFromPathLandscapeConstMeta =>
      const TaskConstMeta(
        debugName: "render_score_from_path_landscape",
        argNames: ["path", "landscape"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ComparisonPageResult dco_decode_comparison_page_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return ComparisonPageResult(
      oursRgba: dco_decode_list_prim_u_8_strict(arr[0]),
      oursWidth: dco_decode_u_32(arr[1]),
      oursHeight: dco_decode_u_32(arr[2]),
      ogRgba: dco_decode_list_prim_u_8_strict(arr[3]),
      ogWidth: dco_decode_u_32(arr[4]),
      ogHeight: dco_decode_u_32(arr[5]),
      diffRgba: dco_decode_list_prim_u_8_strict(arr[6]),
      diffWidth: dco_decode_u_32(arr[7]),
      diffHeight: dco_decode_u_32(arr[8]),
      totalPixels: dco_decode_u_64(arr[9]),
      diffPixels: dco_decode_u_64(arr[10]),
      diffPct: dco_decode_f_64(arr[11]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<OgFixtureInfo> dco_decode_list_og_fixture_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_og_fixture_info).toList();
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RenderCommandDto> dco_decode_list_render_command_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_render_command_dto).toList();
  }

  @protected
  List<ScoreFileEntry> dco_decode_list_score_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_score_file_entry).toList();
  }

  @protected
  OgFixtureInfo dco_decode_og_fixture_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return OgFixtureInfo(
      fixtureName: dco_decode_String(arr[0]),
      ogPdf: dco_decode_String(arr[1]),
      ogPageCount: dco_decode_i_32(arr[2]),
      ourPageCount: dco_decode_i_32(arr[3]),
      ogExists: dco_decode_bool(arr[4]),
    );
  }

  @protected
  RenderCommandDto dco_decode_render_command_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 32)
      throw Exception('unexpected arr length: expect 32 but see ${arr.length}');
    return RenderCommandDto(
      kind: dco_decode_u_8(arr[0]),
      x0: dco_decode_f_64(arr[1]),
      y0: dco_decode_f_64(arr[2]),
      x1: dco_decode_f_64(arr[3]),
      y1: dco_decode_f_64(arr[4]),
      x2: dco_decode_f_64(arr[5]),
      y2: dco_decode_f_64(arr[6]),
      x3: dco_decode_f_64(arr[7]),
      y3: dco_decode_f_64(arr[8]),
      width: dco_decode_f_64(arr[9]),
      height: dco_decode_f_64(arr[10]),
      thickness: dco_decode_f_64(arr[11]),
      lineSpacing: dco_decode_f_64(arr[12]),
      sizePercent: dco_decode_f_64(arr[13]),
      fontSize: dco_decode_f_64(arr[14]),
      dashLen: dco_decode_f_64(arr[15]),
      colorR: dco_decode_f_64(arr[16]),
      colorG: dco_decode_f_64(arr[17]),
      colorB: dco_decode_f_64(arr[18]),
      colorA: dco_decode_f_64(arr[19]),
      glyphCode: dco_decode_u_32(arr[20]),
      glyphCodes: dco_decode_list_prim_u_32_strict(arr[21]),
      nLines: dco_decode_u_8(arr[22]),
      barType: dco_decode_u_8(arr[23]),
      pageNumber: dco_decode_u_32(arr[24]),
      up0: dco_decode_bool(arr[25]),
      up1: dco_decode_bool(arr[26]),
      dashed: dco_decode_bool(arr[27]),
      bold: dco_decode_bool(arr[28]),
      italic: dco_decode_bool(arr[29]),
      text: dco_decode_String(arr[30]),
      fontName: dco_decode_String(arr[31]),
    );
  }

  @protected
  ScoreFileEntry dco_decode_score_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ScoreFileEntry(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      format: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ComparisonPageResult sse_decode_comparison_page_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_oursRgba = sse_decode_list_prim_u_8_strict(deserializer);
    var var_oursWidth = sse_decode_u_32(deserializer);
    var var_oursHeight = sse_decode_u_32(deserializer);
    var var_ogRgba = sse_decode_list_prim_u_8_strict(deserializer);
    var var_ogWidth = sse_decode_u_32(deserializer);
    var var_ogHeight = sse_decode_u_32(deserializer);
    var var_diffRgba = sse_decode_list_prim_u_8_strict(deserializer);
    var var_diffWidth = sse_decode_u_32(deserializer);
    var var_diffHeight = sse_decode_u_32(deserializer);
    var var_totalPixels = sse_decode_u_64(deserializer);
    var var_diffPixels = sse_decode_u_64(deserializer);
    var var_diffPct = sse_decode_f_64(deserializer);
    return ComparisonPageResult(
      oursRgba: var_oursRgba,
      oursWidth: var_oursWidth,
      oursHeight: var_oursHeight,
      ogRgba: var_ogRgba,
      ogWidth: var_ogWidth,
      ogHeight: var_ogHeight,
      diffRgba: var_diffRgba,
      diffWidth: var_diffWidth,
      diffHeight: var_diffHeight,
      totalPixels: var_totalPixels,
      diffPixels: var_diffPixels,
      diffPct: var_diffPct,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<OgFixtureInfo> sse_decode_list_og_fixture_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OgFixtureInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_og_fixture_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RenderCommandDto> sse_decode_list_render_command_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RenderCommandDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_render_command_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ScoreFileEntry> sse_decode_list_score_file_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ScoreFileEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_score_file_entry(deserializer));
    }
    return ans_;
  }

  @protected
  OgFixtureInfo sse_decode_og_fixture_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fixtureName = sse_decode_String(deserializer);
    var var_ogPdf = sse_decode_String(deserializer);
    var var_ogPageCount = sse_decode_i_32(deserializer);
    var var_ourPageCount = sse_decode_i_32(deserializer);
    var var_ogExists = sse_decode_bool(deserializer);
    return OgFixtureInfo(
      fixtureName: var_fixtureName,
      ogPdf: var_ogPdf,
      ogPageCount: var_ogPageCount,
      ourPageCount: var_ourPageCount,
      ogExists: var_ogExists,
    );
  }

  @protected
  RenderCommandDto sse_decode_render_command_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_u_8(deserializer);
    var var_x0 = sse_decode_f_64(deserializer);
    var var_y0 = sse_decode_f_64(deserializer);
    var var_x1 = sse_decode_f_64(deserializer);
    var var_y1 = sse_decode_f_64(deserializer);
    var var_x2 = sse_decode_f_64(deserializer);
    var var_y2 = sse_decode_f_64(deserializer);
    var var_x3 = sse_decode_f_64(deserializer);
    var var_y3 = sse_decode_f_64(deserializer);
    var var_width = sse_decode_f_64(deserializer);
    var var_height = sse_decode_f_64(deserializer);
    var var_thickness = sse_decode_f_64(deserializer);
    var var_lineSpacing = sse_decode_f_64(deserializer);
    var var_sizePercent = sse_decode_f_64(deserializer);
    var var_fontSize = sse_decode_f_64(deserializer);
    var var_dashLen = sse_decode_f_64(deserializer);
    var var_colorR = sse_decode_f_64(deserializer);
    var var_colorG = sse_decode_f_64(deserializer);
    var var_colorB = sse_decode_f_64(deserializer);
    var var_colorA = sse_decode_f_64(deserializer);
    var var_glyphCode = sse_decode_u_32(deserializer);
    var var_glyphCodes = sse_decode_list_prim_u_32_strict(deserializer);
    var var_nLines = sse_decode_u_8(deserializer);
    var var_barType = sse_decode_u_8(deserializer);
    var var_pageNumber = sse_decode_u_32(deserializer);
    var var_up0 = sse_decode_bool(deserializer);
    var var_up1 = sse_decode_bool(deserializer);
    var var_dashed = sse_decode_bool(deserializer);
    var var_bold = sse_decode_bool(deserializer);
    var var_italic = sse_decode_bool(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_fontName = sse_decode_String(deserializer);
    return RenderCommandDto(
      kind: var_kind,
      x0: var_x0,
      y0: var_y0,
      x1: var_x1,
      y1: var_y1,
      x2: var_x2,
      y2: var_y2,
      x3: var_x3,
      y3: var_y3,
      width: var_width,
      height: var_height,
      thickness: var_thickness,
      lineSpacing: var_lineSpacing,
      sizePercent: var_sizePercent,
      fontSize: var_fontSize,
      dashLen: var_dashLen,
      colorR: var_colorR,
      colorG: var_colorG,
      colorB: var_colorB,
      colorA: var_colorA,
      glyphCode: var_glyphCode,
      glyphCodes: var_glyphCodes,
      nLines: var_nLines,
      barType: var_barType,
      pageNumber: var_pageNumber,
      up0: var_up0,
      up1: var_up1,
      dashed: var_dashed,
      bold: var_bold,
      italic: var_italic,
      text: var_text,
      fontName: var_fontName,
    );
  }

  @protected
  ScoreFileEntry sse_decode_score_file_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_format = sse_decode_String(deserializer);
    return ScoreFileEntry(name: var_name, path: var_path, format: var_format);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_comparison_page_result(
    ComparisonPageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.oursRgba, serializer);
    sse_encode_u_32(self.oursWidth, serializer);
    sse_encode_u_32(self.oursHeight, serializer);
    sse_encode_list_prim_u_8_strict(self.ogRgba, serializer);
    sse_encode_u_32(self.ogWidth, serializer);
    sse_encode_u_32(self.ogHeight, serializer);
    sse_encode_list_prim_u_8_strict(self.diffRgba, serializer);
    sse_encode_u_32(self.diffWidth, serializer);
    sse_encode_u_32(self.diffHeight, serializer);
    sse_encode_u_64(self.totalPixels, serializer);
    sse_encode_u_64(self.diffPixels, serializer);
    sse_encode_f_64(self.diffPct, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_og_fixture_info(
    List<OgFixtureInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_og_fixture_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_render_command_dto(
    List<RenderCommandDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_render_command_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_score_file_entry(
    List<ScoreFileEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_score_file_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_og_fixture_info(
    OgFixtureInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fixtureName, serializer);
    sse_encode_String(self.ogPdf, serializer);
    sse_encode_i_32(self.ogPageCount, serializer);
    sse_encode_i_32(self.ourPageCount, serializer);
    sse_encode_bool(self.ogExists, serializer);
  }

  @protected
  void sse_encode_render_command_dto(
    RenderCommandDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.kind, serializer);
    sse_encode_f_64(self.x0, serializer);
    sse_encode_f_64(self.y0, serializer);
    sse_encode_f_64(self.x1, serializer);
    sse_encode_f_64(self.y1, serializer);
    sse_encode_f_64(self.x2, serializer);
    sse_encode_f_64(self.y2, serializer);
    sse_encode_f_64(self.x3, serializer);
    sse_encode_f_64(self.y3, serializer);
    sse_encode_f_64(self.width, serializer);
    sse_encode_f_64(self.height, serializer);
    sse_encode_f_64(self.thickness, serializer);
    sse_encode_f_64(self.lineSpacing, serializer);
    sse_encode_f_64(self.sizePercent, serializer);
    sse_encode_f_64(self.fontSize, serializer);
    sse_encode_f_64(self.dashLen, serializer);
    sse_encode_f_64(self.colorR, serializer);
    sse_encode_f_64(self.colorG, serializer);
    sse_encode_f_64(self.colorB, serializer);
    sse_encode_f_64(self.colorA, serializer);
    sse_encode_u_32(self.glyphCode, serializer);
    sse_encode_list_prim_u_32_strict(self.glyphCodes, serializer);
    sse_encode_u_8(self.nLines, serializer);
    sse_encode_u_8(self.barType, serializer);
    sse_encode_u_32(self.pageNumber, serializer);
    sse_encode_bool(self.up0, serializer);
    sse_encode_bool(self.up1, serializer);
    sse_encode_bool(self.dashed, serializer);
    sse_encode_bool(self.bold, serializer);
    sse_encode_bool(self.italic, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.fontName, serializer);
  }

  @protected
  void sse_encode_score_file_entry(
    ScoreFileEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.format, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
