// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert`, `load_fonts_for_bitmap`, `mac_roman_to_string`, `render_to_bitmaps`, `render_to_dtos`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Load an NGL file from raw bytes and render it to a list of drawing commands.
///
/// Returns an empty vec on parse/interpret failure.
Future<List<RenderCommandDto>> renderNglFromBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiScoreRenderNglFromBytes(data: data);

/// Load a Notelist (.nl) file from UTF-8 text and render it to drawing commands.
///
/// Returns an error string on parse/convert failure (empty string = success).
/// The first element of the returned tuple is the error message (empty on success),
/// the second is the command list.
Future<List<RenderCommandDto>> renderNotelistFromText({required String text}) =>
    RustLib.instance.api.crateApiScoreRenderNotelistFromText(text: text);

/// Load a Notelist (.nl) file from raw bytes (Mac Roman encoded) and render it to drawing commands.
///
/// Notelist files are encoded in Mac Roman (single-byte encoding), not UTF-8.
/// This function accepts raw bytes and decodes them as Mac Roman before parsing.
/// Returns an empty vec on parse/convert failure.
Future<List<RenderCommandDto>> renderNotelistFromBytes(
        {required List<int> data}) =>
    RustLib.instance.api.crateApiScoreRenderNotelistFromBytes(data: data);

/// Load an NGL file from raw bytes and render to page bitmaps.
///
/// `font_dir` is the absolute path to a directory containing Bravura.otf and text fonts.
/// `dpi` controls resolution (72.0 = screen, 144.0 = retina).
/// Returns an empty vec on parse/interpret failure.
Future<List<PageBitmapDto>> renderNglToBitmaps(
        {required List<int> data,
        required String fontDir,
        required double dpi}) =>
    RustLib.instance.api.crateApiScoreRenderNglToBitmaps(
        data: data, fontDir: fontDir, dpi: dpi);

/// Load a Notelist from raw bytes (Mac Roman) and render to page bitmaps.
///
/// `font_dir` is the absolute path to a directory containing Bravura.otf and text fonts.
/// `dpi` controls resolution (72.0 = screen, 144.0 = retina).
/// Returns an empty vec on parse/convert failure.
Future<List<PageBitmapDto>> renderNotelistToBitmaps(
        {required List<int> data,
        required String fontDir,
        required double dpi}) =>
    RustLib.instance.api.crateApiScoreRenderNotelistToBitmaps(
        data: data, fontDir: fontDir, dpi: dpi);

/// Render a score file from a filesystem path (auto-detects .ngl vs .nl).
///
/// Returns an empty vec on failure.
Future<List<RenderCommandDto>> renderScoreFromPath({required String path}) =>
    RustLib.instance.api.crateApiScoreRenderScoreFromPath(path: path);

/// List score files (.ngl and .nl) in a directory.
///
/// Returns entries sorted by name. Non-recursive.
List<ScoreFileEntry> listScoreFiles({required String directory}) =>
    RustLib.instance.api.crateApiScoreListScoreFiles(directory: directory);

/// Render a score file with landscape orientation (for Notelist files).
///
/// NGL files have their own page dimensions embedded, so landscape is ignored.
/// For Notelist files, landscape swaps page width and height (792x612 instead of 612x792).
Future<List<RenderCommandDto>> renderScoreFromPathLandscape(
        {required String path, required bool landscape}) =>
    RustLib.instance.api.crateApiScoreRenderScoreFromPathLandscape(
        path: path, landscape: landscape);

/// Find the project root directory by searching upward from a starting path
/// for a directory containing both `Cargo.toml` and a `tests/` subdirectory.
///
/// Returns the path string if found, empty string otherwise.
String findProjectRoot({required String startPath}) =>
    RustLib.instance.api.crateApiScoreFindProjectRoot(startPath: startPath);

/// Convenience: return the number of render commands for a given NGL file.
int renderCommandCount({required List<int> data}) =>
    RustLib.instance.api.crateApiScoreRenderCommandCount(data: data);

/// Bridge health check.
String bridgeHello() => RustLib.instance.api.crateApiScoreBridgeHello();

/// One page rendered as an RGBA bitmap.
class PageBitmapDto {
  final int width;
  final int height;

  /// Premultiplied RGBA, width * height * 4 bytes.
  final Uint8List rgba;

  const PageBitmapDto({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageBitmapDto &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}

/// Flat DTO for one drawing command.
///
/// `kind` selects the variant. Fields that don't apply are zero/empty.
/// See CMD_* constants for kind values.
class RenderCommandDto {
  final int kind;
  final double x0;
  final double y0;
  final double x1;
  final double y1;
  final double x2;
  final double y2;
  final double x3;
  final double y3;
  final double width;
  final double height;
  final double thickness;
  final double lineSpacing;
  final double sizePercent;
  final double fontSize;
  final double dashLen;
  final double colorR;
  final double colorG;
  final double colorB;
  final double colorA;
  final int glyphCode;
  final Uint32List glyphCodes;
  final int nLines;
  final int barType;
  final int pageNumber;
  final bool up0;
  final bool up1;
  final bool dashed;
  final bool bold;
  final bool italic;
  final String text;
  final String fontName;

  const RenderCommandDto({
    required this.kind,
    required this.x0,
    required this.y0,
    required this.x1,
    required this.y1,
    required this.x2,
    required this.y2,
    required this.x3,
    required this.y3,
    required this.width,
    required this.height,
    required this.thickness,
    required this.lineSpacing,
    required this.sizePercent,
    required this.fontSize,
    required this.dashLen,
    required this.colorR,
    required this.colorG,
    required this.colorB,
    required this.colorA,
    required this.glyphCode,
    required this.glyphCodes,
    required this.nLines,
    required this.barType,
    required this.pageNumber,
    required this.up0,
    required this.up1,
    required this.dashed,
    required this.bold,
    required this.italic,
    required this.text,
    required this.fontName,
  });

  static Future<RenderCommandDto> default_() =>
      RustLib.instance.api.crateApiScoreRenderCommandDtoDefault();

  @override
  int get hashCode =>
      kind.hashCode ^
      x0.hashCode ^
      y0.hashCode ^
      x1.hashCode ^
      y1.hashCode ^
      x2.hashCode ^
      y2.hashCode ^
      x3.hashCode ^
      y3.hashCode ^
      width.hashCode ^
      height.hashCode ^
      thickness.hashCode ^
      lineSpacing.hashCode ^
      sizePercent.hashCode ^
      fontSize.hashCode ^
      dashLen.hashCode ^
      colorR.hashCode ^
      colorG.hashCode ^
      colorB.hashCode ^
      colorA.hashCode ^
      glyphCode.hashCode ^
      glyphCodes.hashCode ^
      nLines.hashCode ^
      barType.hashCode ^
      pageNumber.hashCode ^
      up0.hashCode ^
      up1.hashCode ^
      dashed.hashCode ^
      bold.hashCode ^
      italic.hashCode ^
      text.hashCode ^
      fontName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderCommandDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          x0 == other.x0 &&
          y0 == other.y0 &&
          x1 == other.x1 &&
          y1 == other.y1 &&
          x2 == other.x2 &&
          y2 == other.y2 &&
          x3 == other.x3 &&
          y3 == other.y3 &&
          width == other.width &&
          height == other.height &&
          thickness == other.thickness &&
          lineSpacing == other.lineSpacing &&
          sizePercent == other.sizePercent &&
          fontSize == other.fontSize &&
          dashLen == other.dashLen &&
          colorR == other.colorR &&
          colorG == other.colorG &&
          colorB == other.colorB &&
          colorA == other.colorA &&
          glyphCode == other.glyphCode &&
          glyphCodes == other.glyphCodes &&
          nLines == other.nLines &&
          barType == other.barType &&
          pageNumber == other.pageNumber &&
          up0 == other.up0 &&
          up1 == other.up1 &&
          dashed == other.dashed &&
          bold == other.bold &&
          italic == other.italic &&
          text == other.text &&
          fontName == other.fontName;
}

/// A score file entry for the file browser.
class ScoreFileEntry {
  /// Display name (filename without path).
  final String name;

  /// Full absolute path.
  final String path;

  /// "ngl" or "nl"
  final String format;

  const ScoreFileEntry({
    required this.name,
    required this.path,
    required this.format,
  });

  @override
  int get hashCode => name.hashCode ^ path.hashCode ^ format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScoreFileEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          format == other.format;
}
