// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// List all OG fixtures with metadata.
///
/// `project_root` is the absolute path to the nightingale-modernize directory.
/// Used to locate tests/fixtures/ and tests/og_reference/.
Future<List<OgFixtureInfo>> listOgFixtures({required String projectRoot}) =>
    RustLib.instance.api.crateApiCompareListOgFixtures(
      projectRoot: projectRoot,
    );

/// Get a comparison for a specific fixture page.
///
/// `project_root` is the absolute path to nightingale-modernize.
/// `fixture_name` is e.g. "tc_02".
/// `page_num` is 1-based.
///
/// Returns an empty result if the fixture or page can't be rendered.
Future<ComparisonPageResult> getComparison({
  required String projectRoot,
  required String fixtureName,
  required int pageNum,
}) => RustLib.instance.api.crateApiCompareGetComparison(
  projectRoot: projectRoot,
  fixtureName: fixtureName,
  pageNum: pageNum,
);

/// Result of comparing one page.
class ComparisonPageResult {
  /// Our rendered RGBA bitmap (width * height * 4 bytes)
  final Uint8List oursRgba;
  final int oursWidth;
  final int oursHeight;

  /// OG reference RGBA bitmap
  final Uint8List ogRgba;
  final int ogWidth;
  final int ogHeight;

  /// Diff RGBA bitmap (matching=dimmed, different=red)
  final Uint8List diffRgba;
  final int diffWidth;
  final int diffHeight;

  /// Total pixel count
  final BigInt totalPixels;

  /// Number of differing pixels
  final BigInt diffPixels;

  /// Diff percentage (0.0-100.0)
  final double diffPct;

  const ComparisonPageResult({
    required this.oursRgba,
    required this.oursWidth,
    required this.oursHeight,
    required this.ogRgba,
    required this.ogWidth,
    required this.ogHeight,
    required this.diffRgba,
    required this.diffWidth,
    required this.diffHeight,
    required this.totalPixels,
    required this.diffPixels,
    required this.diffPct,
  });

  @override
  int get hashCode =>
      oursRgba.hashCode ^
      oursWidth.hashCode ^
      oursHeight.hashCode ^
      ogRgba.hashCode ^
      ogWidth.hashCode ^
      ogHeight.hashCode ^
      diffRgba.hashCode ^
      diffWidth.hashCode ^
      diffHeight.hashCode ^
      totalPixels.hashCode ^
      diffPixels.hashCode ^
      diffPct.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComparisonPageResult &&
          runtimeType == other.runtimeType &&
          oursRgba == other.oursRgba &&
          oursWidth == other.oursWidth &&
          oursHeight == other.oursHeight &&
          ogRgba == other.ogRgba &&
          ogWidth == other.ogWidth &&
          ogHeight == other.ogHeight &&
          diffRgba == other.diffRgba &&
          diffWidth == other.diffWidth &&
          diffHeight == other.diffHeight &&
          totalPixels == other.totalPixels &&
          diffPixels == other.diffPixels &&
          diffPct == other.diffPct;
}

/// Information about a fixture with OG reference.
class OgFixtureInfo {
  /// Fixture name (e.g. "tc_02")
  final String fixtureName;

  /// OG reference PDF filename
  final String ogPdf;

  /// Number of pages in the OG PDF (0 if unreadable)
  final int ogPageCount;

  /// Number of pages in our rendering
  final int ourPageCount;

  /// Whether the OG PDF file exists on disk
  final bool ogExists;

  const OgFixtureInfo({
    required this.fixtureName,
    required this.ogPdf,
    required this.ogPageCount,
    required this.ourPageCount,
    required this.ogExists,
  });

  @override
  int get hashCode =>
      fixtureName.hashCode ^
      ogPdf.hashCode ^
      ogPageCount.hashCode ^
      ourPageCount.hashCode ^
      ogExists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OgFixtureInfo &&
          runtimeType == other.runtimeType &&
          fixtureName == other.fixtureName &&
          ogPdf == other.ogPdf &&
          ogPageCount == other.ogPageCount &&
          ourPageCount == other.ourPageCount &&
          ogExists == other.ogExists;
}
